services:
  flandersdb:
    container_name: flandersdb
    image: postgres:17
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /apps/postgresql/data:/var/lib/postgresql/data
      - /apps/postgresql/scripts/:/scripts
    restart: unless-stopped

  flanders:
    container_name: flanders
    image: flanders:latest
    depends_on:
      - flandersdb
    restart: unless-stopped
