services:
  flandersdb:
    container_name: flandersdb
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    volumes:
      - /apps/postgresql/data:/var/lib/postgresql/data
      - /apps/postgresql/scripts/:/scripts