services:
  flandersdb:
    container_name: flandersdb
    image: postgres:17
    env_file:
      - .env
    volumes:
      - flandersdb_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U ned -d flandersdb"
      interval: 5s
      timeout: 5s
      retries: 5

  flanders:
    container_name: flanders
    image: flanders:latest
    build: .
    depends_on:
      flandersdb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=flandersdb
    restart: on-failure

volumes:
  flandersdb_data:
