name: Lint Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup environment
      uses: ./.github/actions/setup

    - name: Ruff check
      run: uv run ruff check

    - name: Pyrefly check
      run: uv run pyrefly check --summarize-errors
